FROM golang:1.20-buster
# The following are unnecessary, as is only used for CI
#checkov:skip=CKV_DOCKER_2: healthcheck
#checkov:skip=CKV_DOCKER_3: user

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
COPY module/terraform.tf .
RUN tfswitch && terraform --version

WORKDIR /workdir/

COPY go.mod .
COPY go.sum .
RUN go mod download
