FROM python:3.11-slim-buster
# The following are unnecessary, as is only used for CI
#checkov:skip=CKV_DOCKER_2: healthcheck
#checkov:skip=CKV_DOCKER_3: user

RUN pip install --upgrade pip \
    pip install checkov \
    pip install pre-commit==2.21.0

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    git \
    shellcheck \
    unzip && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://raw.githubusercontent.com/warrensbox/terraform-switcher/release/install.sh | bash
COPY module/terraform.tf .
RUN tfswitch && terraform --version

RUN curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
RUN tflint --version

WORKDIR /workdir/
RUN git config --global --add safe.directory /workdir
